version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: urlshort-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - urlshort-db-volume:/var/lib/postgresql/data
    networks:
      - urlshort-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - urlshort-network

volumes:
  urlshort-db-volume:

networks:
  urlshort-network:
    driver: bridge
