openapi: 3.0.0
info:
  title: URL Shortener API
  description: API for shortening, resolving, and redirecting URLs
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /shorten:
    post:
      summary: Shorten a URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
              required:
                - url
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
        "400":
          description: Invalid input
        "500":
          description: Internal server error

  /resolve:
    post:
      summary: Resolve a shortened URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
              required:
                - url
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  original_url:
                    type: string
                    format: uri
        "400":
          description: Invalid input
        "500":
          description: Internal server error

  /health:
    get:
      summary: Health check endpoint
      responses:
        "200":
          description: Server is healthy
          content:
            text/plain:
              schema:
                type: string
                example: OK

  /{shortURL}:
    get:
      summary: Redirect to the original URL
      parameters:
        - in: path
          name: shortURL
          required: true
          schema:
            type: string
      responses:
        "301":
          description: Redirect to the original URL
        "404":
          description: Short URL not found
        "500":
          description: Internal server error
